server:
  port: 80

spring:
  application:
    name: consumer-service-consul-80

  cloud:
    consul:
      port: 8500
      host: localhost

      discovery:
        service-name: ${spring.application.name}