server:
  port: 8004

spring:
  application:
    name: payment-provider-8004
  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        service-name: ${spring.application.name}
